---
- name: Install apache2
  apt: pkg=apache2 state=latest

- name: Copy apache vhost config
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-enabled/vhost.conf

- name: enable mod_rewrite
  command: a2enmod rewrite

- name: Start apache
  service: name=apache2 state=started